name: Import Meetup Events

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1' # every Monday at 7am GMT
    - cron: '0 7 * * 4' # every Thursday at 7am GMT

jobs:
  import-meetup:
    if: github.repository == 'silkenodwell/n8n-meetup-summary' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download iCal file
        run: |
          mkdir files
          curl -L "https://www.meetup.com/women-coding-community/events/ical/" -o files/meetup.ics
          
      - name: Cache pip
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('tools/requirements.txt') }}
            restore-keys: |
                ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run Meetup import script
        run: |
            mkdir data
            python meetup_import.py
      
      - name: Post results to n8n
        run: |
            curl -X POST https://silkenodwell.app.n8n.cloud/webhook/1222d6d4-5523-4c47-a3c6-a7eddf6e5f1c -H \
            "Content-Type: application/json" -d @data/events.json

            
